const fs = require("fs");
const assert = require("assert");
const index = fs.readFileSync("index.html", "utf8");
const app = fs.readFileSync("app.js", "utf8");
const server = fs.readFileSync("server.mjs", "utf8");
const css = fs.readFileSync("styles.css", "utf8");
assert.match(index, /เปลี่ยนเรื่องที่คิด/);
assert.match(index, /app\.js\?v=0\.7\.1/);
assert.match(index, /tanjai-video-studio\.onrender\.com/);
assert.match(index, /location\.replace/);
assert.doesNotMatch(index, /ตัดต่อจากคลิปที่มี|CapCut/);
assert.match(app, /เลือกบรรยากาศ/);
assert.match(app, /ทดลอง 1 ฉาก/);
assert.match(app, /รับชุด Prompt/);
assert.match(app, /อนิเมะ/);
assert.match(app, /\/api\/jobs\//);
assert.match(app, /\/api\/health/);
assert.match(app, /ระบบสร้างวิดีโอพร้อมใช้งาน/);
assert.match(server, /openai\("\/videos"/);
assert.match(server, /\/videos\/\$\{video\.id\}\/content/);
assert.match(server, /status: "queued"/);
assert.doesNotMatch(server, /images\/generations|-loop|stillimage|tune.*still/);
assert.match(css, /@media\(max-width:860px\)/);
assert.match(css, /@media\(max-width:640px\)/);
console.log(JSON.stringify({ version: "0.7.1", movingVideo: true, silentFallback: false, promptPack: true, queuedJobs: true, responsive: true, serviceCheck: true, githubRedirect: true, status: "PASS" }, null, 2));
